# Template Parameters:
#
# NAME=${NAME}
# NAMESPACE=${NAMESPACE}
# COMMENT=${COMMENT}
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAME}
  ${COMMENT}namespace: ${EXPORTER_NAMESPACE}
  labels:
    clickhouse.altinity.com/chop: ${OPERATOR_VERSION}
    app: clickhouse-operator
data:
